# Generated by Django 5.2.1 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ALUMNO/A', 'Alumno/a'), ('PROFESOR/A', 'Profesor/a'), ('DIRECTOR/A', 'Director/a'), ('SECRETARIO/A', 'Secretario/a'), ('TUTOR/A', 'Tutor/a')], max_length=12),
        ),
    ]
