# Generated by Django 5.2.1 on 2025-05-28 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('materia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('dia_semana', models.CharField(choices=[('LUNES', 'lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='curso.curso')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='materia.materia')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
