# Generated by Django 5.2.1 on 2025-06-07 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0001_initial'),
        ('alumno_curso', '0002_alter_alumnocurso_id_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_entregada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ENTREGADO', 'Entregado'), ('ATRASADO', 'Atrasado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='actividad.actividad')),
                ('id_alumno_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='alumno_curso.alumnocurso')),
            ],
            options={
                'unique_together': {('id_actividad', 'id_alumno_curso')},
            },
        ),
    ]
