# Generated by Django 5.2.1 on 2025-06-08 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno_curso', '0002_alter_alumnocurso_id_alumno_and_more'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1erT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_2doT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_3erT', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('APROBADO/A', 'Aprobado/a'), ('REPROBADO/A', 'Reprobado/a'), ('EN PROCESO', 'En proceso')], default='EN PROCESO', max_length=12)),
                ('id_alumno_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumen_notas', to='alumno_curso.alumnocurso')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumen_notas', to='materia.materia')),
            ],
            options={
                'unique_together': {('id_alumno_curso', 'id_materia')},
            },
        ),
    ]
