# Generated by Django 5.2.1 on 2025-05-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=3)),
                ('paralelo', models.CharField(max_length=1)),
                ('etapa', models.CharField(default='Secundaria', max_length=10)),
                ('aula', models.CharField(max_length=5)),
            ],
        ),
    ]
