# Generated by Django 5.2.1 on 2025-06-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('dimension_evaluada', '0001_initial'),
        ('materia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateField()),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea'), ('EXAMEN', 'Examen'), ('PRACTICO', 'Práctico'), ('OTRO', 'Otro')], max_length=20)),
                ('gestion', models.IntegerField()),
                ('trimestre', models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')])),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='curso.curso')),
                ('id_dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='dimension_evaluada.dimensionevaluada')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='materia.materia')),
                ('id_profesor', models.ForeignKey(limit_choices_to={'rol': 'PROFESOR/A'}, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
