from django.core.management.base import BaseCommand
from datetime import time

from apps.usuario.models import Usuario
from apps.materia.models import Materia
from apps.curso.models import Curso
from apps.horario.models import Horario


class Command(BaseCommand):
    help = 'Pobla los horarios de 1ro a 6to (A, B, C) para las gestiones 2022-2025'

    def handle(self, *args, **kwargs):
        gestiones = [2022, 2023, 2024, 2025]

        bloques = {
            1: (time(7, 30), time(8, 15)),
            2: (time(8, 15), time(9, 0)),
            3: (time(9, 0), time(9, 45)),
            4: (time(9, 55), time(10, 40)),
            5: (time(10, 40), time(11, 25)),
            6: (time(11, 35), time(12, 20)),
            7: (time(12, 20), time(13, 5)),
        }

        # Importar todos los datos horarios desde los bloques anteriores
        horarios_por_curso = {
            # Incluye aquí todos los bloques del 3ro A, B, C y 4to A, B, C
            ("1ro", "A"): [
                ("LUNES", 1, "Matemáticas", "10001"),
                ("LUNES", 2, "Matemáticas", "10001"),
                ("LUNES", 3, "Ciencias Naturales", "10003"),
                ("LUNES", 4, "Ciencias Naturales", "10003"),
                ("LUNES", 5, "Educación Musical", "10007"),
                ("LUNES", 6, "Educación Musical", "10007"),
                ("LUNES", 7, "Religión y Moral", "10010"),

                ("MARTES", 1, "Técnica Tecnológica", "10002"),
                ("MARTES", 2, "Técnica Tecnológica", "10002"),
                ("MARTES", 3, "Inglés", "10004"),
                ("MARTES", 4, "Inglés", "10004"),
                ("MARTES", 5, "Psicología", "10008"),
                ("MARTES", 6, "Artes Plásticas", "10009"),
                ("MARTES", 7, "Religión y Moral", "10010"),

                ("MIERCOLES", 1, "Matemáticas", "10001"),
                ("MIERCOLES", 2, "Matemáticas", "10001"),
                ("MIERCOLES", 3, "Ciencias Sociales", "10006"),
                ("MIERCOLES", 4, "Ciencias Sociales", "10006"),
                ("MIERCOLES", 5, "Artes Plásticas", "10009"),
                ("MIERCOLES", 6, "Lenguaje", "10011"),
                ("MIERCOLES", 7, "Lenguaje", "10011"),

                ("JUEVES", 1, "Ciencias Naturales", "10003"),
                ("JUEVES", 2, "Ciencias Naturales", "10003"),
                ("JUEVES", 3, "Lenguaje", "10011"),
                ("JUEVES", 4, "Lenguaje", "10011"),
                ("JUEVES", 5, "Matemáticas", "10001"),
                ("JUEVES", 6, "Inglés", "10004"),
                ("JUEVES", 7, "Inglés", "10004"),

                ("VIERNES", 1, "Psicología", "10008"),
                ("VIERNES", 2, "Ciencias Sociales", "10006"),
                ("VIERNES", 3, "Inglés", "10004"),
                ("VIERNES", 4, "Inglés", "10004"),
                ("VIERNES", 5, "Lenguaje", "10011"),
                ("VIERNES", 6, "Educación Física", "10013"),
                ("VIERNES", 7, "Educación Física", "10013"),
            ],
            ("1ro", "B"): [
                ("LUNES", 1, "Ciencias Sociales", "10006"),
                ("LUNES", 2, "Ciencias Sociales", "10006"),
                ("LUNES", 3, "Matemáticas", "10001"),
                ("LUNES", 4, "Matemáticas", "10001"),
                ("LUNES", 5, "Inglés", "10004"),
                ("LUNES", 6, "Inglés", "10004"),
                ("LUNES", 7, "Lenguaje", "10011"),

                ("MARTES", 1, "Psicología", "10008"),
                ("MARTES", 2, "Ciencias Sociales", "10006"),
                ("MARTES", 3, "Educación Musical", "10007"),
                ("MARTES", 4, "Educación Musical", "10007"),
                ("MARTES", 5, "Artes Plásticas", "10009"),
                ("MARTES", 6, "Inglés", "10004"),
                ("MARTES", 7, "Inglés", "10004"),

                ("MIERCOLES", 1, "Artes Plásticas", "10009"),
                ("MIERCOLES", 2, "Ciencias Naturales", "10003"),
                ("MIERCOLES", 3, "Ciencias Naturales", "10003"),
                ("MIERCOLES", 4, "Educación Física", "10013"),
                ("MIERCOLES", 5, "Educación Física", "10013"),
                ("MIERCOLES", 6, "Psicología", "10008"),
                ("MIERCOLES", 7, "Religión y Moral", "10010"),

                ("JUEVES", 1, "Lenguaje", "10011"),
                ("JUEVES", 2, "Lenguaje", "10011"),
                ("JUEVES", 3, "Inglés", "10004"),
                ("JUEVES", 4, "Inglés", "10004"),
                ("JUEVES", 5, "Religión y Moral", "10010"),
                ("JUEVES", 6, "Matemáticas", "10001"),
                ("JUEVES", 7, "Matemáticas", "10001"),

                ("VIERNES", 1, "Técnica Tecnológica", "10002"),
                ("VIERNES", 2, "Técnica Tecnológica", "10002"),
                ("VIERNES", 3, "Lenguaje", "10011"),
                ("VIERNES", 4, "Lenguaje", "10011"),
                ("VIERNES", 5, "Matemáticas", "10001"),
                ("VIERNES", 6, "Ciencias Naturales", "10003"),
                ("VIERNES", 7, "Ciencias Naturales", "10003"),
            ],
            ("1ro", "C"): [
                ("LUNES", 1, "Inglés", "10005"),
                ("LUNES", 2, "Inglés", "10005"),
                ("LUNES", 3, "Lenguaje", "10011"),
                ("LUNES", 4, "Lenguaje", "10011"),
                ("LUNES", 5, "Matemáticas", "10001"),
                ("LUNES", 6, "Educación Física", "10013"),
                ("LUNES", 7, "Educación Física", "10013"),

                ("MARTES", 1, "Ciencias Sociales", "10006"),
                ("MARTES", 2, "Religión y Moral", "10010"),
                ("MARTES", 3, "Artes Plásticas", "10009"),
                ("MARTES", 4, "Matemáticas", "10001"),
                ("MARTES", 5, "Matemáticas", "10001"),
                ("MARTES", 6, "Ciencias Naturales", "10003"),
                ("MARTES", 7, "Ciencias Naturales", "10003"),

                ("MIERCOLES", 1, "Psicología", "10008"),
                ("MIERCOLES", 2, "Lenguaje", "10011"),
                ("MIERCOLES", 3, "Lenguaje", "10011"),
                ("MIERCOLES", 4, "Matemáticas", "10001"),
                ("MIERCOLES", 5, "Matemáticas", "10001"),
                ("MIERCOLES", 6, "Inglés", "10005"),
                ("MIERCOLES", 7, "Inglés", "10005"),

                ("JUEVES", 1, "Inglés", "10005"),
                ("JUEVES", 2, "Inglés", "10005"),
                ("JUEVES", 3, "Técnica Tecnológica", "10002"),
                ("JUEVES", 4, "Técnica Tecnológica", "10002"),
                ("JUEVES", 5, "Ciencias Naturales", "10003"),
                ("JUEVES", 6, "Ciencias Naturales", "10003"),
                ("JUEVES", 7, "Lenguaje", "10011"),

                ("VIERNES", 1, "Religión y Moral", "10010"),
                ("VIERNES", 2, "Artes Plásticas", "10009"),
                ("VIERNES", 3, "Educación Musical", "10007"),
                ("VIERNES", 4, "Educación Musical", "10007"),
                ("VIERNES", 5, "Ciencias Sociales", "10006"),
                ("VIERNES", 6, "Ciencias Sociales", "10006"),
                ("VIERNES", 7, "Psicología", "10008"),
            ],
            ("2do", "A"): [
                ("LUNES", 1, "Lenguaje", "10011"),
                ("LUNES", 2, "Lenguaje", "10011"),
                ("LUNES", 3, "Educación Musical", "10007"),
                ("LUNES", 4, "Educación Musical", "10007"),
                ("LUNES", 5, "Inglés", "10005"),
                ("LUNES", 6, "Inglés", "10005"),
                ("LUNES", 7, "Artes Plásticas", "10009"),

                ("MARTES", 1, "Matemáticas", "10001"),
                ("MARTES", 2, "Matemáticas", "10001"),
                ("MARTES", 3, "Ciencias Sociales", "10006"),
                ("MARTES", 4, "Ciencias Sociales", "10006"),
                ("MARTES", 5, "Religión y Moral", "10010"),
                ("MARTES", 6, "Educación Física", "10013"),
                ("MARTES", 7, "Educación Física", "10013"),

                ("MIERCOLES", 1, "Lenguaje", "10011"),
                ("MIERCOLES", 2, "Inglés", "10005"),
                ("MIERCOLES", 3, "Inglés", "10005"),
                ("MIERCOLES", 4, "Psicología", "10008"),
                ("MIERCOLES", 5, "Ciencias Naturales", "10003"),
                ("MIERCOLES", 6, "Ciencias Naturales", "10003"),
                ("MIERCOLES", 7, "Matemáticas", "10001"),

                ("JUEVES", 1, "Técnica Tecnológica", "10002"),
                ("JUEVES", 2, "Técnica Tecnológica", "10002"),
                ("JUEVES", 3, "Ciencias Sociales", "10006"),
                ("JUEVES", 4, "Religión y Moral", "10010"),
                ("JUEVES", 5, "Lenguaje", "10011"),
                ("JUEVES", 6, "Lenguaje", "10011"),
                ("JUEVES", 7, "Psicología", "10008"),

                ("VIERNES", 1, "Matemáticas", "10001"),
                ("VIERNES", 2, "Matemáticas", "10001"),
                ("VIERNES", 3, "Ciencias Naturales", "10003"),
                ("VIERNES", 4, "Ciencias Naturales", "10003"),
                ("VIERNES", 5, "Inglés", "10005"),
                ("VIERNES", 6, "Inglés", "10005"),
                ("VIERNES", 7, "Artes Plásticas", "10009"),
            ],
            ("2do", "B"): [
                ("LUNES", 1, "Artes Plásticas", "10009"),
                ("LUNES", 2, "Psicología", "10008"),
                ("LUNES", 3, "Inglés", "10005"),
                ("LUNES", 4, "Inglés", "10005"),
                ("LUNES", 5, "Ciencias Sociales", "10006"),
                ("LUNES", 6, "Matemáticas", "10001"),
                ("LUNES", 7, "Matemáticas", "10001"),

                ("MARTES", 1, "Inglés", "10005"),
                ("MARTES", 2, "Inglés", "10005"),
                ("MARTES", 3, "Lenguaje", "10012"),
                ("MARTES", 4, "Ciencias Naturales", "10003"),
                ("MARTES", 5, "Ciencias Naturales", "10003"),
                ("MARTES", 6, "Técnica Tecnológica", "10002"),
                ("MARTES", 7, "Técnica Tecnológica", "10002"),

                ("MIERCOLES", 1, "Ciencias Sociales", "10006"),
                ("MIERCOLES", 2, "Ciencias Sociales", "10006"),
                ("MIERCOLES", 3, "Religión y Moral", "10010"),
                ("MIERCOLES", 4, "Lenguaje", "10012"),
                ("MIERCOLES", 5, "Lenguaje", "10012"),
                ("MIERCOLES", 6, "Educación Física", "10013"),
                ("MIERCOLES", 7, "Educación Física", "10013"),

                ("JUEVES", 1, "Educación Musical", "10007"),
                ("JUEVES", 2, "Educación Musical", "10007"),
                ("JUEVES", 3, "Matemáticas", "10001"),
                ("JUEVES", 4, "Matemáticas", "10001"),
                ("JUEVES", 5, "Inglés", "10005"),
                ("JUEVES", 6, "Inglés", "10005"),
                ("JUEVES", 7, "Religión y Moral", "10010"),

                ("VIERNES", 1, "Ciencias Naturales", "10003"),
                ("VIERNES", 2, "Ciencias Naturales", "10003"),
                ("VIERNES", 3, "Psicología", "10008"),
                ("VIERNES", 4, "Artes Plásticas", "10009"),
                ("VIERNES", 5, "Lenguaje", "10012"),
                ("VIERNES", 6, "Lenguaje", "10012"),
                ("VIERNES", 7, "Matemáticas", "10001"),
            ],
            ("2do", "C"): [
                ("LUNES", 1, "Ciencias Naturales", "10003"),
                ("LUNES", 2, "Ciencias Naturales", "10003"),
                ("LUNES", 3, "Inglés", "10004"),
                ("LUNES", 4, "Inglés", "10004"),
                ("LUNES", 5, "Lenguaje", "10012"),
                ("LUNES", 6, "Técnica Tecnológica", "10002"),
                ("LUNES", 7, "Técnica Tecnológica", "10002"),

                ("MARTES", 1, "Lenguaje", "10012"),
                ("MARTES", 2, "Lenguaje", "10012"),
                ("MARTES", 3, "Religión y Moral", "10010"),
                ("MARTES", 4, "Artes Plásticas", "10009"),
                ("MARTES", 5, "Ciencias Sociales", "10006"),
                ("MARTES", 6, "Ciencias Sociales", "10006"),
                ("MARTES", 7, "Matemáticas", "10001"),

                ("MIERCOLES", 1, "Lenguaje", "10012"),
                ("MIERCOLES", 2, "Lenguaje", "10012"),
                ("MIERCOLES", 3, "Psicología", "10008"),
                ("MIERCOLES", 4, "Artes Plásticas", "10009"),
                ("MIERCOLES", 5, "Educación Musical", "10007"),
                ("MIERCOLES", 6, "Inglés", "10004"),
                ("MIERCOLES", 7, "Inglés", "10004"),

                ("JUEVES", 1, "Matemáticas", "10001"),
                ("JUEVES", 2, "Matemáticas", "10001"),
                ("JUEVES", 3, "Ciencias Naturales", "10003"),
                ("JUEVES", 4, "Ciencias Naturales", "10003"),
                ("JUEVES", 5, "Ciencias Sociales", "10006"),
                ("JUEVES", 6, "Educación Física", "10013"),
                ("JUEVES", 7, "Educación Física", "10013"),

                ("VIERNES", 1, "Inglés", "10004"),
                ("VIERNES", 2, "Inglés", "10004"),
                ("VIERNES", 3, "Matemáticas", "10001"),
                ("VIERNES", 4, "Matemáticas", "10001"),
                ("VIERNES", 5, "Educación Musical", "10007"),
                ("VIERNES", 6, "Psicología", "10008"),
                ("VIERNES", 7, "Religión y Moral", "10010"),
            ],
            ("3ro", "A"): [
                ("LUNES", 1, "Psicología", "10008"),
                ("LUNES", 2, "Artes Plásticas", "10009"),
                ("LUNES", 3, "Ciencias Sociales", "10006"),
                ("LUNES", 4, "Ciencias Sociales", "10006"),
                ("LUNES", 5, "Física", "10017"),
                ("LUNES", 6, "Física", "10017"),
                ("LUNES", 7, "Inglés", "10004"),

                ("MARTES", 1, "Matemáticas", "10014"),
                ("MARTES", 2, "Matemáticas", "10014"),
                ("MARTES", 3, "Educación Física", "10016"),
                ("MARTES", 4, "Educación Física", "10016"),
                ("MARTES", 5, "Ciencias Naturales", "10015"),
                ("MARTES", 6, "Ciencias Naturales", "10015"),
                ("MARTES", 7, "Psicología", "10008"),

                ("MIERCOLES", 1, "Ciencias Naturales", "10015"),
                ("MIERCOLES", 2, "Ciencias Naturales", "10015"),
                ("MIERCOLES", 3, "Inglés", "10004"),
                ("MIERCOLES", 4, "Inglés", "10004"),
                ("MIERCOLES", 5, "Matemáticas", "10014"),
                ("MIERCOLES", 6, "Lenguaje", "10012"),
                ("MIERCOLES", 7, "Lenguaje", "10012"),

                ("JUEVES", 1, "Lenguaje", "10012"),
                ("JUEVES", 2, "Lenguaje", "10012"),
                ("JUEVES", 3, "Artes Plásticas", "10009"),
                ("JUEVES", 4, "Matemáticas", "10014"),
                ("JUEVES", 5, "Matemáticas", "10014"),
                ("JUEVES", 6, "Educación Musical", "10007"),
                ("JUEVES", 7, "Educación Musical", "10007"),

                ("VIERNES", 1, "Química", "10018"),
                ("VIERNES", 2, "Química", "10018"),
                ("VIERNES", 3, "Ciencias Sociales", "10006"),
                ("VIERNES", 4, "Religión y Moral", "10010"),
                ("VIERNES", 5, "Inglés", "10004"),
                ("VIERNES", 6, "Inglés", "10004"),
                ("VIERNES", 7, "Técnica Tecnológica", "10002"),
            ],
            ("3ro", "B"): [
                ("LUNES", 1, "Lenguaje", "10012"),
                ("LUNES", 2, "Lenguaje", "10012"),
                ("LUNES", 3, "Religión y Moral", "10010"),
                ("LUNES", 4, "Matemáticas", "10014"),
                ("LUNES", 5, "Psicología", "10008"),
                ("LUNES", 6, "Ciencias Naturales", "10015"),
                ("LUNES", 7, "Ciencias Naturales", "10015"),

                ("MARTES", 1, "Ciencias Sociales", "10019"),
                ("MARTES", 2, "Ciencias Sociales", "10019"),
                ("MARTES", 3, "Matemáticas", "10014"),
                ("MARTES", 4, "Matemáticas", "10014"),
                ("MARTES", 5, "Inglés", "10004"),
                ("MARTES", 6, "Psicología", "10008"),
                ("MARTES", 7, "Artes Plásticas", "10009"),

                ("MIERCOLES", 1, "Inglés", "10004"),
                ("MIERCOLES", 2, "Inglés", "10004"),
                ("MIERCOLES", 3, "Ciencias Naturales", "10015"),
                ("MIERCOLES", 4, "Ciencias Naturales", "10015"),
                ("MIERCOLES", 5, "Técnica Tecnológica", "10002"),
                ("MIERCOLES", 6, "Matemáticas", "10014"),
                ("MIERCOLES", 7, "Matemáticas", "10014"),

                ("JUEVES", 1, "Inglés", "10004"),
                ("JUEVES", 2, "Inglés", "10004"),
                ("JUEVES", 3, "Ciencias Sociales", "10019"),
                ("JUEVES", 4, "Educación Física", "10016"),
                ("JUEVES", 5, "Educación Física", "10016"),
                ("JUEVES", 6, "Lenguaje", "10012"),
                ("JUEVES", 7, "Lenguaje", "10012"),

                ("VIERNES", 1, "Física", "10017"),
                ("VIERNES", 2, "Física", "10017"),
                ("VIERNES", 3, "Química", "10018"),
                ("VIERNES", 4, "Química", "10018"),
                ("VIERNES", 5, "Artes Plásticas", "10009"),
                ("VIERNES", 6, "Educación Musical", "10007"),
                ("VIERNES", 7, "Educación Musical", "10007"),
            ],
            ("3ro", "C"): [
                ("LUNES", 1, "Matemáticas", "10014"),
                ("LUNES", 2, "Matemáticas", "10014"),
                ("LUNES", 3, "Lenguaje", "10012"),
                ("LUNES", 4, "Lenguaje", "10012"),
                ("LUNES", 5, "Ciencias Sociales", "10019"),
                ("LUNES", 6, "Ciencias Sociales", "10019"),
                ("LUNES", 7, "Inglés", "10005"),

                ("MARTES", 1, "Ciencias Naturales", "10015"),
                ("MARTES", 2, "Ciencias Naturales", "10015"),
                ("MARTES", 3, "Técnica Tecnológica", "10002"),
                ("MARTES", 4, "Inglés", "10005"),
                ("MARTES", 5, "Inglés", "10005"),
                ("MARTES", 6, "Química", "10018"),
                ("MARTES", 7, "Química", "10018"),

                ("MIERCOLES", 1, "Educación Física", "10016"),
                ("MIERCOLES", 2, "Educación Física", "10016"),
                ("MIERCOLES", 3, "Educación Musical", "10007"),
                ("MIERCOLES", 4, "Educación Musical", "10007"),
                ("MIERCOLES", 5, "Ciencias Sociales", "10019"),
                ("MIERCOLES", 6, "Artes Plásticas", "10009"),
                ("MIERCOLES", 7, "Psicología", "10008"),

                ("JUEVES", 1, "Ciencias Naturales", "10015"),
                ("JUEVES", 2, "Ciencias Naturales", "10015"),
                ("JUEVES", 3, "Religión y Moral", "10010"),
                ("JUEVES", 4, "Lenguaje", "10012"),
                ("JUEVES", 5, "Lenguaje", "10012"),
                ("JUEVES", 6, "Matemáticas", "10014"),
                ("JUEVES", 7, "Matemáticas", "10014"),

                ("VIERNES", 1, "Inglés", "10005"),
                ("VIERNES", 2, "Inglés", "10005"),
                ("VIERNES", 3, "Artes Plásticas", "10009"),
                ("VIERNES", 4, "Psicología", "10008"),
                ("VIERNES", 5, "Física", "10017"),
                ("VIERNES", 6, "Física", "10017"),
                ("VIERNES", 7, "Matemáticas", "10014"),
            ],
            ("4to", "A"): [
                ("LUNES", 1, "Inglés", "10004"),
                ("LUNES", 2, "Inglés", "10004"),
                ("LUNES", 3, "Filosofía", "10008"),
                ("LUNES", 4, "Educación Física", "10016"),
                ("LUNES", 5, "Educación Física", "10016"),
                ("LUNES", 6, "Religión y Moral", "10010"),
                ("LUNES", 7, "Matemáticas", "10014"),

                ("MARTES", 1, "Inglés", "10004"),
                ("MARTES", 2, "Inglés", "10004"),
                ("MARTES", 3, "Física", "10017"),
                ("MARTES", 4, "Física", "10017"),
                ("MARTES", 5, "Técnica Tecnológica", "10002"),
                ("MARTES", 6, "Lenguaje", "10012"),
                ("MARTES", 7, "Lenguaje", "10012"),

                ("MIERCOLES", 1, "Matemáticas", "10014"),
                ("MIERCOLES", 2, "Matemáticas", "10014"),
                ("MIERCOLES", 3, "Ciencias Sociales", "10019"),
                ("MIERCOLES", 4, "Ciencias Sociales", "10019"),
                ("MIERCOLES", 5, "Ciencias Naturales", "10015"),
                ("MIERCOLES", 6, "Ciencias Naturales", "10015"),
                ("MIERCOLES", 7, "Artes Plásticas", "10009"),

                ("JUEVES", 1, "Filosofía", "10008"),
                ("JUEVES", 2, "Matemáticas", "10014"),
                ("JUEVES", 3, "Matemáticas", "10014"),
                ("JUEVES", 4, "Artes Plásticas", "10009"),
                ("JUEVES", 5, "Ciencias Sociales", "10019"),
                ("JUEVES", 6, "Ciencias Naturales", "10015"),
                ("JUEVES", 7, "Ciencias Naturales", "10015"),

                ("VIERNES", 1, "Educación Musical", "10007"),
                ("VIERNES", 2, "Educación Musical", "10007"),
                ("VIERNES", 3, "Lenguaje", "10012"),
                ("VIERNES", 4, "Lenguaje", "10012"),
                ("VIERNES", 5, "Química", "10018"),
                ("VIERNES", 6, "Química", "10018"),
                ("VIERNES", 7, "Inglés", "10004"),
            ],
            ("4to", "B"): [
                ("LUNES", 1, "Lenguaje", "10020"),  # María Isabel
                ("LUNES", 2, "Lenguaje", "10020"),
                ("LUNES", 3, "Artes Plásticas", "10009"),
                ("LUNES", 4, "Ciencias Sociales", "10019"),
                ("LUNES", 5, "Matemáticas", "10014"),
                ("LUNES", 6, "Matemáticas", "10014"),
                ("LUNES", 7, "Filosofía", "10008"),

                ("MARTES", 1, "Educación Física", "10016"),
                ("MARTES", 2, "Educación Física", "10016"),
                ("MARTES", 3, "Ciencias Naturales", "10015"),
                ("MARTES", 4, "Ciencias Naturales", "10015"),
                ("MARTES", 5, "Matemáticas", "10014"),
                ("MARTES", 6, "Inglés", "10005"),
                ("MARTES", 7, "Inglés", "10005"),

                ("MIERCOLES", 1, "Lenguaje", "10020"),
                ("MIERCOLES", 2, "Lenguaje", "10020"),
                ("MIERCOLES", 3, "Artes Plásticas", "10009"),
                ("MIERCOLES", 4, "Inglés", "10005"),
                ("MIERCOLES", 5, "Inglés", "10005"),
                ("MIERCOLES", 6, "Ciencias Sociales", "10019"),
                ("MIERCOLES", 7, "Ciencias Sociales", "10019"),

                ("JUEVES", 1, "Química", "10018"),
                ("JUEVES", 2, "Química", "10018"),
                ("JUEVES", 3, "Educación Musical", "10007"),
                ("JUEVES", 4, "Educación Musical", "10007"),
                ("JUEVES", 5, "Filosofía", "10008"),
                ("JUEVES", 6, "Física", "10017"),
                ("JUEVES", 7, "Física", "10017"),

                ("VIERNES", 1, "Ciencias Naturales", "10015"),
                ("VIERNES", 2, "Ciencias Naturales", "10015"),
                ("VIERNES", 3, "Técnica Tecnológica", "10002"),
                ("VIERNES", 4, "Matemáticas", "10014"),
                ("VIERNES", 5, "Matemáticas", "10014"),
                ("VIERNES", 6, "Religión y Moral", "10010"),
                ("VIERNES", 7, "Inglés", "10005"),
            ],
            ("4to", "C"): [
                ("LUNES", 1, "Educación Física", "10016"),
                ("LUNES", 2, "Educación Física", "10016"),
                ("LUNES", 3, "Ciencias Naturales", "10015"),
                ("LUNES", 4, "Ciencias Naturales", "10015"),
                ("LUNES", 5, "Artes Plásticas", "10009"),
                ("LUNES", 6, "Filosofía", "10008"),
                ("LUNES", 7, "Ciencias Sociales", "10019"),

                ("MARTES", 1, "Física", "10017"),
                ("MARTES", 2, "Física", "10017"),
                ("MARTES", 3, "Inglés", "10005"),
                ("MARTES", 4, "Religión y Moral", "10010"),
                ("MARTES", 5, "Lenguaje", "10020"),
                ("MARTES", 6, "Lenguaje", "10020"),
                ("MARTES", 7, "Matemáticas", "10014"),

                ("MIERCOLES", 1, "Educación Musical", "10007"),
                ("MIERCOLES", 2, "Educación Musical", "10007"),
                ("MIERCOLES", 3, "Matemáticas", "10014"),
                ("MIERCOLES", 4, "Matemáticas", "10014"),
                ("MIERCOLES", 5, "Química", "10018"),
                ("MIERCOLES", 6, "Química", "10018"),
                ("MIERCOLES", 7, "Técnica Tecnológica", "10002"),

                ("JUEVES", 1, "Lenguaje", "10020"),
                ("JUEVES", 2, "Lenguaje", "10020"),
                ("JUEVES", 3, "Inglés", "10005"),
                ("JUEVES", 4, "Inglés", "10005"),
                ("JUEVES", 5, "Artes Plásticas", "10009"),
                ("JUEVES", 6, "Ciencias Sociales", "10019"),
                ("JUEVES", 7, "Ciencias Sociales", "10019"),

                ("VIERNES", 1, "Matemáticas", "10014"),
                ("VIERNES", 2, "Matemáticas", "10014"),
                ("VIERNES", 3, "Inglés", "10005"),
                ("VIERNES", 4, "Inglés", "10005"),
                ("VIERNES", 5, "Filosofía", "10008"),
                ("VIERNES", 6, "Ciencias Naturales", "10015"),
                ("VIERNES", 7, "Ciencias Naturales", "10015"),
            ],
        }

        # Reemplaza los [...] con los arrays de horario_data que me compartiste para cada curso

        for gestion in gestiones:
            for (nivel, paralelo), horario_data in horarios_por_curso.items():
                curso = Curso.objects.get(nivel=nivel, paralelo=paralelo)

                for dia, bloque, materia_nombre, ci_profesor in horario_data:
                    hora_inicio, hora_salida = bloques[bloque]
                    materia = Materia.objects.get(nombre=materia_nombre)
                    profesor = Usuario.objects.get(ci=ci_profesor)

                    Horario.objects.create(
                        gestion=gestion,
                        dia_semana=dia,
                        hora_inicio=hora_inicio,
                        hora_salida=hora_salida,
                        id_curso=curso,
                        id_materia=materia,
                        id_profesor=profesor
                    )

        self.stdout.write(self.style.SUCCESS("Horarios de 1ro a 6to (A, B, C) creados para gestiones 2022–2025."))
