# Generated by Django 5.2.1 on 2025-05-29 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_curso', '0001_initial'),
        ('curso', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnocurso',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnocurso',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos_inscritos', to='curso.curso'),
        ),
    ]
