# Generated by Django 5.2.1 on 2025-06-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_curso', '0002_alter_alumnocurso_id_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnocurso',
            name='gestion',
            field=models.IntegerField(default=2025),
        ),
    ]
