# Generated by Django 5.2.1 on 2025-05-24 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno_curso', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField()),
                ('id_alumno_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='alumno_curso.alumnocurso')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='materia.materia')),
            ],
        ),
    ]
