# Generated by Django 5.2.1 on 2025-06-09 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno_curso', '0003_alter_alumnocurso_gestion'),
        ('asistencia', '0001_initial'),
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('fecha', 'id_alumno_curso', 'id_materia'), name='unique_asistencia_alumno_fecha_materia'),
        ),
    ]
