# Generated by Django 5.2.1 on 2025-06-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionEvaluada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Ser', 'Ser'), ('Saber', 'Saber'), ('Hacer', 'Hacer'), ('Decidir', 'Decidir'), ('Autoevaluación', 'Autoevaluación')], max_length=30, unique=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
